DROP TABLE IF EXISTS users, categories, locations, events, requests, compilations;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250)                               NOT NULL,
    email VARCHAR(254)                              NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                                   NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                           NOT NULL,
    lon FLOAT                                           NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120)                               NOT NULL,
    annotation VARCHAR(2000)                         NOT NULL,
    description VARCHAR(7000)                        NOT NULL,
    category_id BIGINT                               NOT NULL,
    initiator BIGINT                                 NOT NULL,
    location_id BIGINT,
    paid BOOLEAN                                     NOT NULL,
    request_moderation BOOLEAN DEFAULT TRUE          NOT NULL,
    participant_limit  BIGINT DEFAULT 25             NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(20)                                NOT NULL,
    available BOOLEAN DEFAULT TRUE                   NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id),
    CONSTRAINT user_event FOREIGN KEY (initiator) REFERENCES users (user_id),
    CONSTRAINT category_event FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT location_event FOREIGN KEY (location_id) REFERENCES locations (location_id)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event      BIGINT                                  NOT NULL,
    requester  BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT user_request FOREIGN KEY (requester) REFERENCES users (user_id),
    CONSTRAINT event_request FOREIGN KEY (event) REFERENCES events (event_id),
    CONSTRAINT events_user UNIQUE (event, requester)
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(50)                                  NOT NULL,
    events    VARCHAR,
    pinned    BOOLEAN DEFAULT FALSE                        NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);